package com.bom.entidades;
// Generated 17-may-2019 17:43:44 by Hibernate Tools 4.3.1



/**
 * Archivos generated by hbm2java
 */
public class Archivos  implements java.io.Serializable {


     private int arcId;
     private ServicioRequisitos servicioRequisitos;
     private Solicitud solicitud;
     private Short archivo;

    public Archivos() {
    }

	
    public Archivos(int arcId) {
        this.arcId = arcId;
    }
    public Archivos(int arcId, ServicioRequisitos servicioRequisitos, Solicitud solicitud, Short archivo) {
       this.arcId = arcId;
       this.servicioRequisitos = servicioRequisitos;
       this.solicitud = solicitud;
       this.archivo = archivo;
    }
   
    public int getArcId() {
        return this.arcId;
    }
    
    public void setArcId(int arcId) {
        this.arcId = arcId;
    }
    public ServicioRequisitos getServicioRequisitos() {
        return this.servicioRequisitos;
    }
    
    public void setServicioRequisitos(ServicioRequisitos servicioRequisitos) {
        this.servicioRequisitos = servicioRequisitos;
    }
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public Short getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(Short archivo) {
        this.archivo = archivo;
    }




}


