package com.bom.entidades;
// Generated 17-may-2019 17:43:44 by Hibernate Tools 4.3.1



/**
 * FacturaDetalle generated by hbm2java
 */
public class FacturaDetalle  implements java.io.Serializable {


     private int fadId;
     private FacturaCabecera facturaCabecera;
     private Servicio servicio;
     private String descripcion;
     private int cantidad;
     private double precio;
     private double total;

    public FacturaDetalle() {
    }

	
    public FacturaDetalle(int fadId, String descripcion, int cantidad, double precio, double total) {
        this.fadId = fadId;
        this.descripcion = descripcion;
        this.cantidad = cantidad;
        this.precio = precio;
        this.total = total;
    }
    public FacturaDetalle(int fadId, FacturaCabecera facturaCabecera, Servicio servicio, String descripcion, int cantidad, double precio, double total) {
       this.fadId = fadId;
       this.facturaCabecera = facturaCabecera;
       this.servicio = servicio;
       this.descripcion = descripcion;
       this.cantidad = cantidad;
       this.precio = precio;
       this.total = total;
    }
   
    public int getFadId() {
        return this.fadId;
    }
    
    public void setFadId(int fadId) {
        this.fadId = fadId;
    }
    public FacturaCabecera getFacturaCabecera() {
        return this.facturaCabecera;
    }
    
    public void setFacturaCabecera(FacturaCabecera facturaCabecera) {
        this.facturaCabecera = facturaCabecera;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }




}


