package com.bom.entidades;
// Generated 17-may-2019 17:43:44 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FacturaCabecera generated by hbm2java
 */
public class FacturaCabecera  implements java.io.Serializable {


     private int facId;
     private Persona persona;
     private Solicitud solicitud;
     private Date fecha;
     private String tipoDocumento;
     private String tipoCuenta;
     private double total;
     private Set<PermisoFuncionamiento> permisoFuncionamientos = new HashSet<PermisoFuncionamiento>(0);
     private Set<FacturaDetalle> facturaDetalles = new HashSet<FacturaDetalle>(0);

    public FacturaCabecera() {
    }

	
    public FacturaCabecera(int facId, Date fecha, String tipoDocumento, String tipoCuenta, double total) {
        this.facId = facId;
        this.fecha = fecha;
        this.tipoDocumento = tipoDocumento;
        this.tipoCuenta = tipoCuenta;
        this.total = total;
    }
    public FacturaCabecera(int facId, Persona persona, Solicitud solicitud, Date fecha, String tipoDocumento, String tipoCuenta, double total, Set<PermisoFuncionamiento> permisoFuncionamientos, Set<FacturaDetalle> facturaDetalles) {
       this.facId = facId;
       this.persona = persona;
       this.solicitud = solicitud;
       this.fecha = fecha;
       this.tipoDocumento = tipoDocumento;
       this.tipoCuenta = tipoCuenta;
       this.total = total;
       this.permisoFuncionamientos = permisoFuncionamientos;
       this.facturaDetalles = facturaDetalles;
    }
   
    public int getFacId() {
        return this.facId;
    }
    
    public void setFacId(int facId) {
        this.facId = facId;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getTipoCuenta() {
        return this.tipoCuenta;
    }
    
    public void setTipoCuenta(String tipoCuenta) {
        this.tipoCuenta = tipoCuenta;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public Set<PermisoFuncionamiento> getPermisoFuncionamientos() {
        return this.permisoFuncionamientos;
    }
    
    public void setPermisoFuncionamientos(Set<PermisoFuncionamiento> permisoFuncionamientos) {
        this.permisoFuncionamientos = permisoFuncionamientos;
    }
    public Set<FacturaDetalle> getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set<FacturaDetalle> facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }




}


