package com.bom.entidades;
// Generated 17-may-2019 17:43:44 by Hibernate Tools 4.3.1



/**
 * InspeccionDetalle generated by hbm2java
 */
public class InspeccionDetalle  implements java.io.Serializable {


     private int indId;
     private InspecionCabecera inspecionCabecera;
     private Requisitos requisitos;
     private String estado;
     private String tipo;
     private int cantidad;
     private String capacidad;
     private String ubicacion;
     private String tiene;

    public InspeccionDetalle() {
    }

	
    public InspeccionDetalle(int indId, String estado, String tipo, int cantidad, String capacidad, String ubicacion, String tiene) {
        this.indId = indId;
        this.estado = estado;
        this.tipo = tipo;
        this.cantidad = cantidad;
        this.capacidad = capacidad;
        this.ubicacion = ubicacion;
        this.tiene = tiene;
    }
    public InspeccionDetalle(int indId, InspecionCabecera inspecionCabecera, Requisitos requisitos, String estado, String tipo, int cantidad, String capacidad, String ubicacion, String tiene) {
       this.indId = indId;
       this.inspecionCabecera = inspecionCabecera;
       this.requisitos = requisitos;
       this.estado = estado;
       this.tipo = tipo;
       this.cantidad = cantidad;
       this.capacidad = capacidad;
       this.ubicacion = ubicacion;
       this.tiene = tiene;
    }
   
    public int getIndId() {
        return this.indId;
    }
    
    public void setIndId(int indId) {
        this.indId = indId;
    }
    public InspecionCabecera getInspecionCabecera() {
        return this.inspecionCabecera;
    }
    
    public void setInspecionCabecera(InspecionCabecera inspecionCabecera) {
        this.inspecionCabecera = inspecionCabecera;
    }
    public Requisitos getRequisitos() {
        return this.requisitos;
    }
    
    public void setRequisitos(Requisitos requisitos) {
        this.requisitos = requisitos;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public String getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(String capacidad) {
        this.capacidad = capacidad;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getTiene() {
        return this.tiene;
    }
    
    public void setTiene(String tiene) {
        this.tiene = tiene;
    }




}


