package com.bom.entidades;
// Generated 17-may-2019 17:43:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PermisoFuncionamiento generated by hbm2java
 */
public class PermisoFuncionamiento  implements java.io.Serializable {


     private int pefId;
     private FacturaCabecera facturaCabecera;
     private Date fechaCreacion;
     private Date fechaVencimiento;

    public PermisoFuncionamiento() {
    }

	
    public PermisoFuncionamiento(int pefId, Date fechaCreacion, Date fechaVencimiento) {
        this.pefId = pefId;
        this.fechaCreacion = fechaCreacion;
        this.fechaVencimiento = fechaVencimiento;
    }
    public PermisoFuncionamiento(int pefId, FacturaCabecera facturaCabecera, Date fechaCreacion, Date fechaVencimiento) {
       this.pefId = pefId;
       this.facturaCabecera = facturaCabecera;
       this.fechaCreacion = fechaCreacion;
       this.fechaVencimiento = fechaVencimiento;
    }
   
    public int getPefId() {
        return this.pefId;
    }
    
    public void setPefId(int pefId) {
        this.pefId = pefId;
    }
    public FacturaCabecera getFacturaCabecera() {
        return this.facturaCabecera;
    }
    
    public void setFacturaCabecera(FacturaCabecera facturaCabecera) {
        this.facturaCabecera = facturaCabecera;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }




}


