package com.bom.entidades;
// Generated 17-may-2019 17:43:44 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int perId;
     private String nombre;
     private String apellido;
     private String dni;
     private String direccion;
     private String telefono;
     private String estadoCivil;
     private String sexo;
     private String EMail;
     private String estado;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set<InspecionCabecera> inspecionCabeceras = new HashSet<InspecionCabecera>(0);
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);
     private Set<FacturaCabecera> facturaCabeceras = new HashSet<FacturaCabecera>(0);
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

    public Persona() {
    }

	
    public Persona(int perId, String nombre, String apellido, String dni, String telefono, Date fechaCreacion, Date fechaModificacion) {
        this.perId = perId;
        this.nombre = nombre;
        this.apellido = apellido;
        this.dni = dni;
        this.telefono = telefono;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
    }
    public Persona(int perId, String nombre, String apellido, String dni, String direccion, String telefono, String estadoCivil, String sexo, String EMail, String estado, Date fechaCreacion, Date fechaModificacion, Set<InspecionCabecera> inspecionCabeceras, Set<Usuarios> usuarioses, Set<FacturaCabecera> facturaCabeceras, Set<Solicitud> solicituds) {
       this.perId = perId;
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.direccion = direccion;
       this.telefono = telefono;
       this.estadoCivil = estadoCivil;
       this.sexo = sexo;
       this.EMail = EMail;
       this.estado = estado;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.inspecionCabeceras = inspecionCabeceras;
       this.usuarioses = usuarioses;
       this.facturaCabeceras = facturaCabeceras;
       this.solicituds = solicituds;
    }
   
    public int getPerId() {
        return this.perId;
    }
    
    public void setPerId(int perId) {
        this.perId = perId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<InspecionCabecera> getInspecionCabeceras() {
        return this.inspecionCabeceras;
    }
    
    public void setInspecionCabeceras(Set<InspecionCabecera> inspecionCabeceras) {
        this.inspecionCabeceras = inspecionCabeceras;
    }
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }
    public Set<FacturaCabecera> getFacturaCabeceras() {
        return this.facturaCabeceras;
    }
    
    public void setFacturaCabeceras(Set<FacturaCabecera> facturaCabeceras) {
        this.facturaCabeceras = facturaCabeceras;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }




}


