package com.bom.entidades;
// Generated 17-may-2019 17:43:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Requisitos generated by hbm2java
 */
public class Requisitos  implements java.io.Serializable {


     private int reqId;
     private String nombre;
     private String descripcion;
     private String llenadopor;
     private Set<InspeccionDetalle> inspeccionDetalles = new HashSet<InspeccionDetalle>(0);
     private Set<ServicioRequisitos> servicioRequisitoses = new HashSet<ServicioRequisitos>(0);

    public Requisitos() {
    }

	
    public Requisitos(int reqId, String nombre, String descripcion, String llenadopor) {
        this.reqId = reqId;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.llenadopor = llenadopor;
    }
    public Requisitos(int reqId, String nombre, String descripcion, String llenadopor, Set<InspeccionDetalle> inspeccionDetalles, Set<ServicioRequisitos> servicioRequisitoses) {
       this.reqId = reqId;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.llenadopor = llenadopor;
       this.inspeccionDetalles = inspeccionDetalles;
       this.servicioRequisitoses = servicioRequisitoses;
    }
   
    public int getReqId() {
        return this.reqId;
    }
    
    public void setReqId(int reqId) {
        this.reqId = reqId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getLlenadopor() {
        return this.llenadopor;
    }
    
    public void setLlenadopor(String llenadopor) {
        this.llenadopor = llenadopor;
    }
    public Set<InspeccionDetalle> getInspeccionDetalles() {
        return this.inspeccionDetalles;
    }
    
    public void setInspeccionDetalles(Set<InspeccionDetalle> inspeccionDetalles) {
        this.inspeccionDetalles = inspeccionDetalles;
    }
    public Set<ServicioRequisitos> getServicioRequisitoses() {
        return this.servicioRequisitoses;
    }
    
    public void setServicioRequisitoses(Set<ServicioRequisitos> servicioRequisitoses) {
        this.servicioRequisitoses = servicioRequisitoses;
    }




}


