package com.bom.entidades;
// Generated 17-may-2019 17:43:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ServicioRequisitos generated by hbm2java
 */
public class ServicioRequisitos  implements java.io.Serializable {


     private int sreId;
     private Requisitos requisitos;
     private Servicio servicio;
     private Set<Archivos> archivoses = new HashSet<Archivos>(0);

    public ServicioRequisitos() {
    }

	
    public ServicioRequisitos(int sreId) {
        this.sreId = sreId;
    }
    public ServicioRequisitos(int sreId, Requisitos requisitos, Servicio servicio, Set<Archivos> archivoses) {
       this.sreId = sreId;
       this.requisitos = requisitos;
       this.servicio = servicio;
       this.archivoses = archivoses;
    }
   
    public int getSreId() {
        return this.sreId;
    }
    
    public void setSreId(int sreId) {
        this.sreId = sreId;
    }
    public Requisitos getRequisitos() {
        return this.requisitos;
    }
    
    public void setRequisitos(Requisitos requisitos) {
        this.requisitos = requisitos;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public Set<Archivos> getArchivoses() {
        return this.archivoses;
    }
    
    public void setArchivoses(Set<Archivos> archivoses) {
        this.archivoses = archivoses;
    }




}


