package com.bom.entidades;
// Generated 17-may-2019 17:43:44 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private int solId;
     private Persona persona;
     private Servicio servicio;
     private String numeroDeSolicitud;
     private String nombreComercial;
     private String direccion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String estado;
     private String observacion;
     private String estadoDePago;
     private Set<FacturaCabecera> facturaCabeceras = new HashSet<FacturaCabecera>(0);
     private Set<InspecionCabecera> inspecionCabeceras = new HashSet<InspecionCabecera>(0);
     private Set<Archivos> archivoses = new HashSet<Archivos>(0);

    public Solicitud() {
    }

	
    public Solicitud(int solId, String numeroDeSolicitud, String nombreComercial, String direccion, Date fechaCreacion, Date fechaModificacion, String estado, String observacion, String estadoDePago) {
        this.solId = solId;
        this.numeroDeSolicitud = numeroDeSolicitud;
        this.nombreComercial = nombreComercial;
        this.direccion = direccion;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.estado = estado;
        this.observacion = observacion;
        this.estadoDePago = estadoDePago;
    }
    public Solicitud(int solId, Persona persona, Servicio servicio, String numeroDeSolicitud, String nombreComercial, String direccion, Date fechaCreacion, Date fechaModificacion, String estado, String observacion, String estadoDePago, Set<FacturaCabecera> facturaCabeceras, Set<InspecionCabecera> inspecionCabeceras, Set<Archivos> archivoses) {
       this.solId = solId;
       this.persona = persona;
       this.servicio = servicio;
       this.numeroDeSolicitud = numeroDeSolicitud;
       this.nombreComercial = nombreComercial;
       this.direccion = direccion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estado = estado;
       this.observacion = observacion;
       this.estadoDePago = estadoDePago;
       this.facturaCabeceras = facturaCabeceras;
       this.inspecionCabeceras = inspecionCabeceras;
       this.archivoses = archivoses;
    }
   
    public int getSolId() {
        return this.solId;
    }
    
    public void setSolId(int solId) {
        this.solId = solId;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public String getNumeroDeSolicitud() {
        return this.numeroDeSolicitud;
    }
    
    public void setNumeroDeSolicitud(String numeroDeSolicitud) {
        this.numeroDeSolicitud = numeroDeSolicitud;
    }
    public String getNombreComercial() {
        return this.nombreComercial;
    }
    
    public void setNombreComercial(String nombreComercial) {
        this.nombreComercial = nombreComercial;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getEstadoDePago() {
        return this.estadoDePago;
    }
    
    public void setEstadoDePago(String estadoDePago) {
        this.estadoDePago = estadoDePago;
    }
    public Set<FacturaCabecera> getFacturaCabeceras() {
        return this.facturaCabeceras;
    }
    
    public void setFacturaCabeceras(Set<FacturaCabecera> facturaCabeceras) {
        this.facturaCabeceras = facturaCabeceras;
    }
    public Set<InspecionCabecera> getInspecionCabeceras() {
        return this.inspecionCabeceras;
    }
    
    public void setInspecionCabeceras(Set<InspecionCabecera> inspecionCabeceras) {
        this.inspecionCabeceras = inspecionCabeceras;
    }
    public Set<Archivos> getArchivoses() {
        return this.archivoses;
    }
    
    public void setArchivoses(Set<Archivos> archivoses) {
        this.archivoses = archivoses;
    }




}


