package com.bom.entidades;
// Generated 17-may-2019 17:43:44 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int usuId;
     private Persona persona;
     private String usuario;
     private String password;
     private String tipoUsuario;

    public Usuarios() {
    }

	
    public Usuarios(int usuId, String usuario, String password, String tipoUsuario) {
        this.usuId = usuId;
        this.usuario = usuario;
        this.password = password;
        this.tipoUsuario = tipoUsuario;
    }
    public Usuarios(int usuId, Persona persona, String usuario, String password, String tipoUsuario) {
       this.usuId = usuId;
       this.persona = persona;
       this.usuario = usuario;
       this.password = password;
       this.tipoUsuario = tipoUsuario;
    }
   
    public int getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(int usuId) {
        this.usuId = usuId;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }




}


